# Generated by Django 3.2.3 on 2021-05-26 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mydictionary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeDict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('de_meaning', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EnDict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('meaning', models.TextField()),
                ('synonyms', models.TextField()),
                ('antonym', models.TextField()),
                ('repeat', models.BooleanField()),
                ('hard', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ZhDict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zh_meaning', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Dictionary',
        ),
        migrations.AddField(
            model_name='endict',
            name='ch_meaning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mydictionary.zhdict'),
        ),
        migrations.AddField(
            model_name='endict',
            name='ge_meaning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mydictionary.dedict'),
        ),
    ]
